<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ng_fastyoutube"
 *
 * Auto generated by Extension Builder 2017-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fast loading YouTube Video',
	'description' => 'TYPO3 Plugin that displays YouTube-videos faster by loading the video-player on demand while displaying a cacheable preview picture.',
	'category' => 'plugin',
	'author' => 'Roderick Braun',
	'author_email' => 'roderick.braun@ph-freiburg.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
