<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ng_fastyoutube"
 *
 * Auto generated by Extension Builder 2017-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'YouTubeVideo',
	'description' => 'Plugin to display YouTube-videos faster on a page by displaying only a picture and loading the video-player first on demand.',
	'category' => 'plugin',
	'author' => 'Roderick Braun',
	'author_email' => 'roderick.braun@ph-freiburg.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
